image:
  - Visual Studio 2017
  - Ubuntu

matrix:
  fast_finish: true

install:
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/vostok/devtools/master/library-ci/install-cement.ps1" -Out "install-cement.ps1"
  - ps: ./install-cement.ps1
  - cmd: %cm% self-update

shallow_clone: true  



build: off

build_script:
  - cmd: echo "build"



test: off

test_script:
  - cmd: echo "test"

