image:
  - Visual Studio 2017
  - Ubuntu

matrix:
  fast_finish: true

install:
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/vostok/devtools/master/library-ci/install-cement.ps1" -Out "install-cement.ps1"
  - ps: ./install-cement.ps1